name: daily_basket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.3
  image_picker: ^0.8.7+4
  path: ^1.9.0
  pdf: ^3.11.1
  printing: ^5.13.2
  firebase_core: ^2.24.2
  sensors_plus: ^5.0.1
  shimmer: ^2.0.0

  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  http: ^1.1.0






  mailer: ^6.0.1
  shared_preferences: ^2.1.0
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/groceries.json
    - assets/fonts/