// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuO2ZIHVKWc3DUxc6vyB-435BgAG_uv3M',
    appId: '1:487965641101:web:e5f58bbb409793594b95c4',
    messagingSenderId: '487965641101',
    projectId: 'flutterapp-40e09',
    authDomain: 'flutterapp-40e09.firebaseapp.com',
    storageBucket: 'flutterapp-40e09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9GbL2Y3Uqq_SlQGAiqzU0JEBGe0HG8WE',
    appId: '1:487965641101:android:c2decde9b44f03fe4b95c4',
    messagingSenderId: '487965641101',
    projectId: 'flutterapp-40e09',
    storageBucket: 'flutterapp-40e09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXXS6voy2E_1nG8XcvRks5fWiWkv7sdcg',
    appId: '1:487965641101:ios:4cab396646ff22a94b95c4',
    messagingSenderId: '487965641101',
    projectId: 'flutterapp-40e09',
    storageBucket: 'flutterapp-40e09.firebasestorage.app',
    iosBundleId: 'com.example.dailybasket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXXS6voy2E_1nG8XcvRks5fWiWkv7sdcg',
    appId: '1:487965641101:ios:4cab396646ff22a94b95c4',
    messagingSenderId: '487965641101',
    projectId: 'flutterapp-40e09',
    storageBucket: 'flutterapp-40e09.firebasestorage.app',
    iosBundleId: 'com.example.dailybasket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuO2ZIHVKWc3DUxc6vyB-435BgAG_uv3M',
    appId: '1:487965641101:web:e5f58bbb409793594b95c4',
    messagingSenderId: '487965641101',
    projectId: 'flutterapp-40e09',
    authDomain: 'flutterapp-40e09.firebaseapp.com',
    storageBucket: 'mybazar-f1627.firebasestorage.app',
  );
}